In [2]:
import numpy as np

a = np.array([[10, 12, 16, 11],
              [5, 4, 6, 12],
              [18, 21, 7, 21]])

In [35]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [9]:
a.shape

(3, 4)

In [120]:
b= np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12],
             [13, 14, 15, 16],
             [17, 18, 19, 20]])

In [16]:
np.abs(a-b).sum(axis=0)

array([ 66.  , 225.  ,  17.89,  75.1 ])

In [38]:
np.abs(a-b).sum(axis=1)

array([39,  7, 33])

In [33]:
np.abs(a-b).sum(axis=1)

array([122.4 , 108.28, 153.31])

In [42]:
sum(np.abs(a[1]-b[2].T))

15

In [45]:
a.reshape(-1,3)

array([[10, 12, 16],
       [11,  5,  4],
       [ 6, 12, 18],
       [21,  7, 21]])

In [48]:
a.reshape(-1,2)

array([[10, 12],
       [16, 11],
       [ 5,  4],
       [ 6, 12],
       [18, 21],
       [ 7, 21]])

In [50]:
a.reshape(-1,4)

array([[10, 12, 16, 11],
       [ 5,  4,  6, 12],
       [18, 21,  7, 21]])

In [51]:
x1 = np.array([1, 2, 3, 4, 5])

In [52]:
x2 = np.array([5, 4, 3])

In [55]:
x1_new = x1[:, np.newaxis];
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [129]:
np.abs(a[:, np.newaxis]-b).sum(axis=2)

array([[39, 23,  9, 11, 25],
       [17,  7, 15, 31, 47],
       [57, 41, 33, 25, 17]])

In [107]:
a[:, np.newaxis]

array([[[10, 12, 16, 11]],

       [[ 5,  4,  6, 12]],

       [[18, 21,  7, 21]]])

In [115]:
[print(i) for i in a[:, np.newaxis]]

[[10 12 16 11]]
[[ 5  4  6 12]]
[[18 21  7 21]]


[None, None, None]

In [125]:
a[:,np.newaxis].shape

(3, 1, 4)

In [119]:
a[0].shape

(4,)

In [122]:
a.shape, b.shape

((3, 4), (5, 4))

In [132]:
ss2 = np.zeros((3,5), np.float32)
ss2 = np.abs(a[:, np.newaxis]-b).sum(axis=2)

In [133]:
ss2

array([[39, 23,  9, 11, 25],
       [17,  7, 15, 31, 47],
       [57, 41, 33, 25, 17]])

In [151]:
a

array([[10, 11, 12, 16],
       [ 4,  5,  6, 12],
       [ 7, 18, 21, 21]])

In [127]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [112]:
a[0]-b

array([[ 9, 10, 13,  7],
       [ 5,  6,  9,  3],
       [ 1,  2,  5, -1],
       [-3, -2,  1, -5]])

In [114]:
(a[0]-b).sum(axis=1)

array([39, 23,  7, -9])

In [54]:
x2+x1_new

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [78]:
ss = np.array(np.zeros((3,3), np.float32))
for i in range(len(a)):
        ss[i] = np.abs(a[i]-b).sum(axis=1)

In [79]:
ss

array([[39., 23.,  9.],
       [17.,  7., 15.],
       [57., 41., 33.]], dtype=float32)

In [92]:
i = np.arange(3)

In [93]:
i

array([0, 1, 2])

In [90]:
ss1 = np.abs(a-b).sum(axis=1)

In [91]:
ss1

array([39,  7, 33])

In [64]:
np.zeros(len(a))

array([0., 0., 0.])

In [60]:
np.abs(a[0]-b).sum(axis=1)

array([39, 23,  9])

In [68]:
np.abs(a[0]-b)

(3, 4)

In [134]:
a

array([[10, 12, 16, 11],
       [ 5,  4,  6, 12],
       [18, 21,  7, 21]])

In [180]:
k=2
for i in a:
    print(np.sort(i)[:k])

[10 11]
[4 5]
[ 7 18]


In [171]:
z=[]
for i in aa:
    z.append(np.argsort(i)[:2])

In [175]:
np.array(z[0])

array([1, 0])

In [152]:
aa = [[5,3,7,89],
      [11,1,2,0],
      [9,24,1,4]]

In [179]:
print([aa[0][i] for i in z[0]])

[3, 5]


In [27]:
s = np.array([1,2,3,4,5,6,7,8,9,10])

In [28]:
s.shape

(10,)

In [2]:
k=3

In [29]:
for el in s:
    aa = [i for i in s if i!=el]
    print(aa)

[2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
s = np.array_split(s,4)

In [31]:
print(s)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [36]:
for el in range(len(s)):
    aa = list([s[i] for i in range(len(s)) if i!=el])
    print(aa)

[array([4, 5, 6]), array([7, 8]), array([ 9, 10])]
[array([1, 2, 3]), array([7, 8]), array([ 9, 10])]
[array([1, 2, 3]), array([4, 5, 6]), array([ 9, 10])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [7]:
s = np.array([1,2,3,4,5,6,7,8,9,10])

In [88]:
s[-1]

10

In [38]:
num = len(s)

In [62]:
def move(arr):
    return [arr[i-1] for i in range(len(arr))]

In [70]:
s = np.array_split(s,4)
s

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]

In [77]:
np.concatenate(s[:2])

array([1, 2, 3, 4, 5, 6])

In [79]:
a

array([[10, 12, 16, 11],
       [ 5,  4,  6, 12],
       [18, 21,  7, 21]])

In [80]:
a = np.array_split(a,3)

In [83]:
a

[array([[10, 12, 16, 11]]),
 array([[ 5,  4,  6, 12]]),
 array([[18, 21,  7, 21]])]

In [82]:
np.concatenate(a[1:])

array([[ 5,  4,  6, 12],
       [18, 21,  7, 21]])

In [84]:
a=move(a)
a

[array([[18, 21,  7, 21]]),
 array([[10, 12, 16, 11]]),
 array([[ 5,  4,  6, 12]])]

In [85]:
np.concatenate(a[1:])

array([[10, 12, 16, 11],
       [ 5,  4,  6, 12]])

In [2]:
def sq(x):
    return x*x, x*x*x

In [5]:
sq(2)[1]

8

In [9]:
np.exp(s)/np.exp(s).sum()

array([7.80134161e-05, 2.12062451e-04, 5.76445508e-04, 1.56694135e-03,
       4.25938820e-03, 1.15782175e-02, 3.14728583e-02, 8.55520989e-02,
       2.32554716e-01, 6.32149258e-01])

In [12]:
def softmax(predictions):
    predictions -= np.max(predictions)
    return np.exp(predictions)/np.exp(predictions).sum()

In [13]:
softmax(np.array([1000, 0, 0]))

array([1., 0., 0.])

In [14]:
np.log(s)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [15]:
softmax(np.array([-5, 0, 5]))

array([4.50940412e-05, 6.69254912e-03, 9.93262357e-01])

In [18]:
zz = np.zeros(3)
zz

array([0., 0., 0.])

In [19]:
zz[2]+=1

In [20]:
zz

array([0., 0., 1.])

In [27]:
zz = np.array([[1],
               [2],
               [3]])

In [42]:
a[:,1]

array([12,  4, 21])

In [35]:
np.matrix([1 if x == id else 0 for x in zz])

matrix([[0, 0, 0]])

In [37]:
0*np.log(4.50940412e-05)+1

1.0

In [101]:
aa=np.array([0,2,1])
z=np.zeros([3,4])
print(z,aa)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [0 2 1]


In [82]:
for i in range(len(zz)):
    z[i,aa[i]]+=1
z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [84]:
a = np.array([[10, 12, 16, 11],
              [5, 4, 6, 12],
              [18, 21, 7, 21]])

In [94]:
a.shape

(3, 4)

In [89]:
np.array([a[i,p] for i,p in enumerate(aa)]).sum()

37

In [92]:
[print(a[:,el]) for el in aa]

[10  5 18]
[16  6  7]
[12  4 21]


[None, None, None]

In [93]:
print(a[:,0])

[10  5 18]


In [85]:
for i,p in enumerate(aa):
    z[i,p] = 1
    print(i,p)
z

0 0
1 1
2 2


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [72]:
a

array([[10, 12, 16, 11],
       [ 5,  4,  6, 12],
       [18, 21,  7, 21]])

In [80]:
for i in range(len(a)):
    a[i,aa[i]] = 0
a

array([[ 0, 12, 16, 11],
       [ 5,  0,  6, 12],
       [18, 21,  0, 21]])

In [102]:
a[range(3),aa]

array([10,  6, 21])

In [99]:
[range(3),aa]

[range(0, 3), array([0, 2, 1])]

In [109]:
aa[range(1),np.array[1]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [76]:
print([1 if i==aa[i] else 0 for i in range(len(aa))])

[1, 1, 1]


In [110]:
np.ones_like(np.array([2.0,3.0]))

array([1., 1.])

In [114]:
a = np.arange(6).reshape(2,3)
print(a)
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print(it.multi_index)
    it.iternext()

[[0 1 2]
 [3 4 5]]
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


In [4]:
batch_size = 100
num_train = 9000
np.arange(batch_size, num_train, batch_size).shape

(89,)

In [5]:
a

array([[10, 12, 16, 11],
       [ 5,  4,  6, 12],
       [18, 21,  7, 21]])

In [6]:
indec = [0,1]

In [11]:
for i in a[indec]:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29]
[50 51 52 53 54 55 56 57 58 59]
[10 11 12 13 14 15 16 17 18 19]
[70 71 72 73 74 75 76 77 78 79]
[40 41 42 43 44 45 46 47 48 49]


In [8]:
a = np.arange(100).reshape(10,10)

In [9]:
indec = [0,2,5,1,7,4]

In [3]:
X = np.array([[1,-2,3],
              [-1, 2, 0.1]
              ])
X, X.shape

(array([[ 1. , -2. ,  3. ],
        [-1. ,  2. ,  0.1]]), (2, 3))

In [4]:
W = 0.001 * np.random.randn(3, 4)

In [6]:
B = 0.001 * np.random.randn(1, 4)

In [8]:
np.dot(X,W)+B

array([[-3.10330192e-03, -4.95164422e-03,  9.46401114e-05,
         1.57294645e-03],
       [ 2.17982645e-03,  2.59483023e-03,  9.89543146e-04,
        -2.39899221e-03]])

In [9]:
class Param:
    """
    Trainable parameter of the model
    Captures both parameter value and the gradient
    """

    def __init__(self, value):
        self.value = value
        self.grad = np.zeros_like(value)

In [11]:
W = Param(0.001 * np.random.randn(3, 4))
B = Param(0.001 * np.random.randn(1, 4))

In [14]:
W.value, W.grad

(array([[-0.00162124, -0.00127288,  0.00057105,  0.00145027],
        [-0.00147432,  0.00046348, -0.00085702,  0.00226754],
        [ 0.00042614, -0.0008374 , -0.00118086,  0.00035139]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [15]:
a = {"w": 3}

In [16]:
a["w"]

3

In [17]:
a = b = 0

In [8]:
a.reshape(1,-1)

array([[10, 12, 16, 11,  5,  4,  6, 12, 18, 21,  7, 21]])

In [9]:
class SubsetSampler(Sampler):
    r"""Samples elements with given indices sequentially

    Arguments:
        indices (ndarray): indices of the samples to take
    """

    def __init__(self, indices):
        self.indices = indices

    def __iter__(self):
        return (self.indices[i] for i in range(len(self.indices)))

    def __len__(self):
        return len(self.indices)

In [11]:
[i for i in SubsetSampler(a)]

[array([10, 12, 16, 11]), array([ 5,  4,  6, 12]), array([18, 21,  7, 21])]

In [13]:
c = np.arange(10)

In [14]:
d = np.arange(0,20,2)

In [18]:
d[d==6]

array([6])

In [20]:
np.where(d==6)[0]

array([3])

In [24]:
d = np.array([1,2,3,4,5,6,5,4,3,2])

In [26]:
np.where(d==3)[0]

array([2, 8])

In [28]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.where((d==3)&(c==2))[0]

array([2])

In [46]:
a = np.ones([3,3])
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
padding = 1

In [47]:
b = np.zeros([2,len(a)+2*padding,len(a)+2*padding])
b

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [48]:
b[:,padding:-padding,padding:-padding] = a

In [49]:
b, b.shape

(array([[[0., 0., 0., 0., 0.],
         [0., 1., 1., 1., 0.],
         [0., 1., 1., 1., 0.],
         [0., 1., 1., 1., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 1., 1., 1., 0.],
         [0., 1., 1., 1., 0.],
         [0., 1., 1., 1., 0.],
         [0., 0., 0., 0., 0.]]]), (2, 5, 5))

In [60]:
res = np.zeros([b.shape[0],b.shape[1]-a.shape[0]+1,b.shape[2]-a.shape[1]+1])
res

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
for x in range(b.shape[0]-a.shape[0]+1):
    for y in range(b.shape[0]-a.shape[0]+1):
        res[:,x,y] = np.sum(np.sum(a*b[:,x:x+3,y:y+3],axis=1),axis=1)
res, res.shape

(array([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]), (2, 3, 3))

In [63]:
[np.sum(a*i[0:3,0:3]) for i in b]

[4.0, 4.0]

In [23]:
b.shape[0]-a.shape[0]+2*padding+1

5

In [2]:
in_channels = 3

In [3]:
filter_size = 3

In [4]:
padding = 1

In [10]:
image = np.ones([in_channels, 5, 5])
image[1,:,:]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
f = np.ones([filter_size,filter_size,in_channels])+1
f.shape

(3, 3, 3)

In [26]:
padded[:,0:3,0:3].shape

(3, 3, 3)

In [15]:
padded = np.zeros((in_channels,image.shape[1]+2*padding, image.shape[1]+2*padding))

In [16]:
padded.shape

(3, 7, 7)

In [17]:
padded[:,padding:-padding,padding:-padding] =image

In [18]:
padded.reshape(1,-1).shape

(1, 147)

In [19]:
f.reshape(-1,1).shape

(27, 1)

In [22]:
res = np.zeros([padded.shape[1]-f.shape[1]+1,padded.shape[2]-f.shape[2]+1])
res

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
for x in range(res.shape[0]):
    for y in range(res.shape[0]):
        res[x,y] = np.sum(f*padded[:,x:x+3,y:y+3])

In [29]:
res

array([[24., 36., 36., 36., 24.],
       [36., 54., 54., 54., 36.],
       [36., 54., 54., 54., 36.],
       [36., 54., 54., 54., 36.],
       [24., 36., 36., 36., 24.]])

In [30]:
for x in range(res.shape[0]):
    for y in range(res.shape[0]):
        res[x,y] = np.dot(padded[:,x:x+3,y:y+3].reshape(1,-1),f.reshape(-1,1))

In [31]:
res

array([[24., 36., 36., 36., 24.],
       [36., 54., 54., 54., 36.],
       [36., 54., 54., 54., 36.],
       [36., 54., 54., 54., 36.],
       [24., 36., 36., 36., 24.]])

In [32]:
def zero_pad(X, pad):
    """
    Pad with zeros all images of the dataset X. The padding is applied to the height and width of an image, 
    as illustrated in Figure 1.
    
    Argument:
    X -- python numpy array of shape (m, n_H, n_W, n_C) representing a batch of m images
    pad -- integer, amount of padding around each image on vertical and horizontal dimensions
    
    Returns:
    X_pad -- padded image of shape (m, n_H + 2*pad, n_W + 2*pad, n_C)
    """
    
    ### START CODE HERE ### (≈ 1 line)
    X_pad = np.pad(X, ((0,0), (pad,pad), (pad,pad), (0,0)), 'constant', constant_values = (0,0))
    ### END CODE HERE ###
    
    return X_pad

In [37]:
zero_pad(np.ones([3,5,5,3]),1)[1,:,:,1]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
def pad(X,p):
    if p>0:
        padded = np.zeros([X.shape[0],X.shape[1]+2*p,X.shape[2]+2*p,X.shape[3]]) 
        padded[:,p:-p,p:-p,:] = X
    else:
        padded = X
    return padded

In [39]:
pad(np.ones([3,5,5,3]),1)[1,:,:,1]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [56]:
for x in range(res.shape[0]):
    for y in range(res.shape[0]):
        res[x,y] = np.dot(pad(image[np.newaxis,:],1)[:,x:x+3,y:y+3,:].reshape(1,-1),f.reshape(-1,1))

In [57]:
res.shape

(5, 5)

In [58]:
res

array([[24., 36., 36., 36., 24.],
       [36., 54., 54., 54., 36.],
       [36., 54., 54., 54., 36.],
       [36., 54., 54., 54., 36.],
       [24., 36., 36., 36., 24.]])

In [55]:
f.shape

(3, 3, 3)

In [43]:
image[np.newaxis,:].shape

(1, 3, 5, 5)

In [52]:
pad(image[np.newaxis,:],1).shape

(1, 7, 7, 3)

In [49]:
image = image.reshape(5,5,3)

In [51]:
image[:,:,1]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
image = np.ones([5,5,5,3])

In [61]:
f = np.ones([3,3,3,2]) + 1

In [66]:
res = np.zeros([5,5,5,2])

In [67]:
for x in range(res.shape[0]):
    for y in range(res.shape[0]):
        res[x,y] = np.dot(pad(image,1)[:,x:x+3,y:y+3,:].reshape(5,-1),f.reshape(-1,2))

In [63]:
pad(image,1).shape

(5, 7, 7, 3)

In [70]:
res[1,:,:,1]

array([[36., 36., 36., 36., 36.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [36., 36., 36., 36., 36.]])

In [74]:
pad(image,0).shape

(5, 5, 5, 3)

In [75]:
X = np.array([
              [
               [[1.0], [2.0]],
               [[0.0], [-1.0]]
              ]
              ,
              [
               [[0.0], [1.0]],
               [[-2.0], [-1.0]]
              ]
             ])

In [76]:
X.shape

(2, 2, 2, 1)

In [77]:
f = np.ones([2,2,1,1])

In [91]:
res = np.zeros([2,1,1,1])
for x in range(1):
    for y in range(1):
        res[:,x,y,:] = np.dot(pad(X,0)[:,x:x+2,y:y+2,:].reshape(2,-1),f.reshape(-1,1))

In [93]:
res.shape

(2, 1, 1, 1)

In [80]:
X.reshape(2,-1).shape

(2, 4)

In [83]:
pad(X,0).reshape(2,-1).shape

(2, 4)

In [85]:
f.reshape(-1,1).shape

(4, 1)

In [86]:
np.dot(pad(X,0).reshape(2,-1),f.reshape(-1,1))

array([[ 2.],
       [-2.]])

In [89]:
pad(X,0)[:,0:2,0:2,:].reshape(2,-1).shape

(2, 4)

In [94]:
batch = 5
H = 5
W = 5
out_ch = 2
out = np.ones([batch, H,W, out_ch])

In [97]:
filter_size = 3
in_ch = 3
f = np.ones([filter_size,filter_size,in_ch,out_ch])+1

In [103]:
grad = np.dot(out[:,0:3,0:3,:].reshape(batch,-1), f.reshape([-1,in_ch]))

In [106]:
out[:,0:3,0:3,:].reshape(batch,filter_size,filter_size,-1).shape

(5, 3, 3, 2)

In [107]:
f.reshape([-1,filter_size,filter_size, in_ch]).shape

(2, 3, 3, 3)

In [104]:
grad.shape

(5, 3)

In [108]:
out1 = np.zeros([1,1,1,1])+3
out1

array([[[[3.]]]])

In [114]:
f1 = np.array([[1,-1],[0,2]])
f1 = f1[:,:,np.newaxis, np.newaxis]
f1.shape

(2, 2, 1, 1)

In [122]:
grad = f1.reshape(2,2,-1)*out1
grad.shape

(1, 2, 2, 1)

In [125]:
z = np.arange(18).reshape(3,3,2)
z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [126]:
z[:,:,1]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [129]:
z.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])

In [131]:
w = np.arange(20,38).reshape(3,3,2)
w

array([[[20, 21],
        [22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37]]])

In [133]:
np.dot(z.reshape(1,-1),w.reshape(-1,1))

array([[4845]])

In [25]:
image = np.arange(54).reshape(2,3,3,3)

In [137]:
f = np.linspace(0,1,num=27).reshape(3,3,3,1)

In [139]:
out = np.dot(image.reshape(2,-1),f.reshape(-1,1))
out, out.shape

(array([[238.5],
        [603. ]]), (2, 1))

In [142]:
outg = np.array([[1],[2]])
outg.shape

(2, 1)

In [145]:
grad = np.dot(outg,f.reshape(-1,1).T).reshape(2,3,3,3)
grad.shape

(2, 3, 3, 3)

In [2]:
outg = np.linspace(0,0.9,16).reshape(2,2,2,2)

In [3]:
f = np.arange(54).reshape(3,3,3,2)

In [4]:
grad = np.zeros([2,4,4,3])

In [151]:
grad[:,0:2,0:2,:].shape

(2, 2, 2, 3)

In [157]:
grad[:,0:3,0:3,:] += np.dot(outg[:,1,1], f.reshape(-1,1).T).reshape(2,3,3,3)

In [170]:
np.dot(outg[:,1,1],f.reshape(-1,2).T)

array([[ 0.42,  1.98,  3.54,  5.1 ,  6.66,  8.22,  9.78, 11.34, 12.9 ,
        14.46, 16.02, 17.58, 19.14, 20.7 , 22.26, 23.82, 25.38, 26.94,
        28.5 , 30.06, 31.62, 33.18, 34.74, 36.3 , 37.86, 39.42, 40.98],
       [ 0.9 ,  4.38,  7.86, 11.34, 14.82, 18.3 , 21.78, 25.26, 28.74,
        32.22, 35.7 , 39.18, 42.66, 46.14, 49.62, 53.1 , 56.58, 60.06,
        63.54, 67.02, 70.5 , 73.98, 77.46, 80.94, 84.42, 87.9 , 91.38]])

In [171]:
grad[:,0:3,0:3,:].shape

(2, 3, 3, 3)

In [173]:
outg.shape

(2, 2, 2, 2)

In [177]:
outg.reshape(-1,2).shape

(8, 2)

In [179]:
np.sum(outg.reshape(-1,2),axis=0).shape

(2,)

In [175]:
f.shape

(3, 3, 3, 2)

In [176]:
np.dot(grad[:,0:3,0:3,:].reshape(-1,2), outg[:,1,1,:].reshape(2,-1)).shape

(27, 2)

In [168]:
f.reshape(-1,1).T.shape

(1, 54)

In [160]:
outg.shape[1],outg.shape[2]

(2, 2)

In [153]:
outg[:,1,1]

array([[0.25714286],
       [0.6       ]])

In [155]:
np.dot(outg[:,1,1], f.reshape(-1,1).T).shape

(2, 27)

In [156]:
grad[:,0:3,0:3,:].shape

(2, 3, 3, 3)

In [161]:
for x in range(outg.shape[1]):
    for y in range(outg.shape[2]):
        grad[:,x:x+3,y:y+3,:] += np.dot(outg[:,x,y], f.reshape(-1,1).T).reshape(2,3,3,3)

In [162]:
grad.shape

(2, 4, 4, 3)

In [185]:
X = np.ones([20,5])

In [186]:
np.mean(X, axis=0).shape

(5,)

In [183]:
X.mean(axis=1).shape

(2, 2, 1)

In [189]:
outg.reshape(2,-1).mean(axis=0).shape

(8,)

In [6]:
outg[:,1,1].reshape(-1,2).mean(axis=0).shape

(2,)

In [7]:
X = np.array([
              [
               [[1.0, 0.0], [2.0, 1.0]],
               [[0.0, -1.0], [-1.0, -2.0]]
              ]
              ,
              [
               [[0.0, 1.0], [1.0, -1.0]],
               [[-2.0, 2.0], [-1.0, 0.0]]
              ]
             ])

print("Shape of X:", X.shape)

Shape of X: (2, 2, 2, 2)


In [ ]:
in_channels=2, out_channels=2, filter_size=2, padding=0

In [9]:
w = np.ones([2,2,2,2])

In [13]:
res = np.zeros([2,1,1,2])
for x in range(1):
    for y in range(1):
        res[:,x,y,:] = np.dot(pad(X,0)[:,x:x+2,y:y+2,:].reshape(2,-1),w.reshape(-1,2))

In [14]:
res.shape

(2, 1, 1, 2)

In [15]:
X[:,0:-0,0:-0,:].shape

(2, 0, 0, 2)

In [22]:
X_back = np.zeros([2,2,2,2])
for x in range(res.shape[1]):
    for y in range(res.shape[2]):
        X_back[:,x:x+2,y:y+2,:] += np.dot(res[:,x,y], w.reshape(-1,2).T).reshape(2,2,2,2)

In [17]:
res[:,x,y].shape

(2, 2)

In [21]:
w.reshape(-1,2).T.shape

(2, 8)

In [23]:
X_back.shape

(2, 2, 2, 2)

In [46]:
image[0,0:2,0:2,0]

array([[ 0,  3],
       [ 9, 12]])

In [47]:
image = np.arange(96).reshape(2,4,4,3)

In [48]:
image.shape

(2, 4, 4, 3)

In [50]:
image[0,:,:,0]

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45]])

In [81]:
pool = np.zeros([2,2,2,3])
size = 2 
for x in range(2):
    xs = size*x
    pool[:,x,x,:] = image[:,xs:xs+size,xs:xs+size,:].reshape(2,-1,3).max(axis=1).reshape(2,3)

In [58]:
image[0,0:2,0:2,1]

array([[ 1,  4],
       [13, 16]])

In [82]:
pool[0,0,0,0]

15.0

In [83]:
pool

array([[[[15., 16., 17.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [45., 46., 47.]]],


       [[[63., 64., 65.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [93., 94., 95.]]]])

In [76]:
size = 2 
for x in range(2):
    xs = size*x
    print(image[:,xs:xs+size,xs:xs+size,:].reshape(2,-1,3).max(axis=1).reshape(2,3))

[[15 16 17]
 [63 64 65]]
[[45 46 47]
 [93 94 95]]


In [70]:
image[:,0:2,0:2,:].reshape(2,-1,3).max(axis=1).reshape(2,3)

array([[15, 16, 17],
       [63, 64, 65]])

In [80]:
pool[:,0,0,:]=image[:,0:2,0:2,:].reshape(2,-1,3).max(axis=1).reshape(2,3)

In [72]:
image[0,:,:,0]

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45]])

In [73]:
image[0,:,:,1]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

In [74]:
image[0,:,:,2]

array([[ 2,  5,  8, 11],
       [14, 17, 20, 23],
       [26, 29, 32, 35],
       [38, 41, 44, 47]])

In [84]:
image.shape

(2, 4, 4, 3)

In [85]:
pool.shape

(2, 2, 2, 3)

In [93]:
for batch in range(2):
    for size1 in range(2):
        for size2 in range(2):
            for chan in range(3):
                pool[batch,size1,size2,chan] = image[batch, size1:size1+2,size2:size2+2,chan].reshape(-1,1).max()

In [91]:
image[0,0:2,0:2,0].reshape(-1,1).max()

15

In [94]:
pool

array([[[[15., 16., 17.],
         [18., 19., 20.]],

        [[27., 28., 29.],
         [30., 31., 32.]]],


       [[[63., 64., 65.],
         [66., 67., 68.]],

        [[75., 76., 77.],
         [78., 79., 80.]]]])

In [96]:
pool[0,:,:,0]

array([[15., 18.],
       [27., 30.]])

In [99]:
image[:,0:2,0:2,:].shape

(2, 2, 2, 3)

In [105]:
back = np.random.randn(24).reshape(2,2,2,3)

In [111]:
image_back = np.zeros([2,4,4,3])

In [102]:
def create_mask_from_window(x):
    """
    Creates a mask from an input matrix x, to identify the max entry of x.
    
    Arguments:
    x -- Array of shape (f, f)
    
    Returns:
    mask -- Array of the same shape as window, contains a True at the position corresponding to the max entry of x.
    """
    
    ### START CODE HERE ### (≈1 line)
    mask = x == np.max(x)
    ### END CODE HERE ###
    
    return mask

In [116]:
for batch in range(2):
    for size1 in range(2):
        for size2 in range(2):
            for chan in range(3):
                image_back[batch,size1:size1+2,size2:size2+2,chan] += create_mask_from_window(image[batch,size1:size1+2,size2:size2+2,chan])*back[batch,size1,size2,chan]

In [110]:
create_mask_from_window(image[0,0:2,0:2,0])*back[0,0,0,0]

array([[0.        , 0.        ],
       [0.        , 0.07459577]])

In [112]:
create_mask_from_window(image[1,0:2,0:2,1])*back[1,0,0,1]

array([[0.        , 0.        ],
       [0.        , 1.86274396]])

In [113]:
image[1,0:2,0:2,1]

array([[49, 52],
       [61, 64]])

In [117]:
image_back

array([[[[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.07459577,  2.16543676,  0.37768754],
         [-0.29557817,  0.67957333, -0.06597642],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 1.2263403 ,  0.49151777,  0.07554984],
         [-0.44895511, -0.01799059, -0.8565185 ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]]],


       [[[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0. 

In [3]:
X = np.array([
              [
               [[1.0, 0.0], [2.0, 1.0]],
               [[0.0, -1.0], [-1.0, -2.0]]
              ]
              ,
              [
               [[0.0, 1.0], [1.0, -1.0]],
               [[-2.0, 2.0], [-1.0, 0.0]]
              ]
             ])

print("Shape of X:", X.shape)

Shape of X: (2, 2, 2, 2)


In [6]:
pool = np.zeros([2,1,1,2])
for batch in range(2):
    for size1 in range(1):
        for size2 in range(1):
            for chan in range(2):
                pool[batch,size1,size2,chan] = X[batch, size1:size1+2,size2:size2+2,chan].reshape(-1,1).max()

In [7]:
pool

array([[[[2., 1.]]],


       [[[1., 2.]]]])

In [38]:
pool

array([[[[12., 13., 14.],
         [12., 13., 14.]],

        [[12., 13., 14.],
         [12., 13., 14.]]],


       [[[39., 40., 41.],
         [39., 40., 41.]],

        [[39., 40., 41.],
         [39., 40., 41.]]]])

In [40]:
image[:,0:2,0:2,:]

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 9, 10, 11],
         [12, 13, 14]]],


       [[[27, 28, 29],
         [30, 31, 32]],

        [[36, 37, 38],
         [39, 40, 41]]]])

(2, 3)

In [32]:
image[:,0:2,0:2,:].reshape(2,-1,3).max(axis=1).reshape(2,1,1,3)

array([[[[12, 13, 14]]],


       [[[39, 40, 41]]]])